### ISSUE TITLE
-[DTBonjourDataConnection isOpen] returns false negatives

### ISSUE THREAD

**Issue by natesymer** [Cocoanetics/DTBonjour#11]
Currently, `-[DTBonjourDataConnection isOpen]` checks to see if the input and output streams are both anything but open (if their streamStatus != open, then the method returns NO). This is not the correct behavior.

A more enlightened approach would be to check if the streams are _closed_:

```
- (BOOL)isOpen {
    if (!_inputStream) return NO;
    if (!_outputStream) return NO;

    if (NSStreamStatusClosed == _inputStream.streamStatus) return NO;
    if (NSStreamStatusClosed == _outputStream.streamStatus) return NO;

    return YES;
} 
```

Furthermore, Apple documentation says that specific stream statuses denote that the connection is indeed open and useable, but some form of metadata is being loaded about said connection. The current approach ignores this detail.

**Comment by Cocoanetics** [comment]
@fhsjaagshs Please send a pull request. your reasoning sounds logical.

**Comment by odrobnik** [comment]
I think that was already merged somehow.
