### ISSUE TITLE
Possible Thread Issue

### ISSUE THREAD

**Issue by MatthewCawley** [Cocoanetics/DTBonjour#13]
I'm not sure if this is an issue or I am misunderstanding the way something works.

The following method `- (BOOL)sendObject:(id)object error:(NSError **)error`
 in DTBonjourConnection makes a call to `[self _startOutput];` on the Main Thread.

Am I right in thinking that when the data is being written to the output stream that this is happening on the Main Thread? Should this not be happening on a background for performance and parallelization of commands?

**Comment by odrobnik** [comment]
@MatthewCawley you are right. This was done so that the delegate methods are all called on the main queue. But certainly the sending could also be done on a background queue.

**Comment by MatthewCawley** [comment]
Hi @odrobnik 

Thanks for confirming that. It may be better to replace the GCD call for the main thread with a background thread call to ensure that part of the code is run on the background.

With regards to the delegate there are 2 approaches that would work. 

1: Wrap the delegate callback methods in a GCD call to the main thread
2: As the method is not a UI based method, it would not necessarily be expected that the delegate call back returns on the main thread. In this case leave the onus on handling the response in a main thread in the hands of the implementor.

**Comment by odrobnik** [comment]
@MatthewCawley you are welcome to make the suggested modifications and test them in the context of where you are using DTBonjour.

**Comment by MatthewCawley** [comment]
Thank you @odrobnik 

I have made the changes and created a pull request for them.

**Comment by odrobnik** [comment]
merged it.
